use_frameworks!
platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
target 'SwiftEmptyData_Example' do
  pod 'SwiftEmptyData', :path => '../'
  pod 'SwiftBrick'
 
end
